### ISSUE TITLE
Shipt Shopper App

### ISSUE THREAD

**Issue by calebmichaelsanchez** [shipt/osmosis#75]
This is not a code issue I am reporting on. I am just a former React developer turned shipt shopper (mainly because I'm a bad dev), but there are some serious issues with State management in the shipt shopper app. It has issues that affect the productivity and efficiency of every single order, and no matter how hard I try I can't seem to contact the right people who care. So here I am. Resurrecting my github account to make a comment on this repo. 

I love working for shipt, and the issues aren't even really that bad, but when I have to troubleshoot the same things every single order it starts to build and makes me wonder why certain things aren't being addressed. Anyway. I'm happy to chat with any engineer who is interested, shit maybe you're already working on the problems I'm dealing with, but I figured I'd reach out here anyway.

**Comment by TomMahle** [comment]
Thanks for reaching out and helping to improve the shopper app experience. I've sent you an e-mail to get some more details on what you're seeing.
